steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/airms-backend:${_ENVIRONMENT}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/airms-backend:latest'
      - '.'
    id: 'build-backend'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/airms-backend:${_ENVIRONMENT}']
    id: 'push-backend'
    waitFor: ['build-backend']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/airms-backend:${_ENVIRONMENT}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'ENV=${_ENVIRONMENT}'
    id: 'deploy-backend'
    waitFor: ['push-backend']

substitutions:
  _ENVIRONMENT: 'dev'
  _REGION: 'us-central1'
  _SERVICE_NAME: 'airms-backend-dev'

images:
  - 'gcr.io/$PROJECT_ID/airms-backend:${_ENVIRONMENT}'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
